label: 'UZH BIO390'
tagline: 'Introduction to Bioinformatics'
description: |
  This is the repository for the University of Zurich's "Introduction to
  Bioinformatics" lecture series.
keywords: UZH, life sciences, baudisgroup. bioinformatics
site_domain_name: http://compbiozurich.org
url: 'https://compbiozurich.org'

# The baseurl parameter is an empty string if the site is represented at the root
# of a domain. For project domains on Github it corresponds to the project name.
baseurl: "/UZH-BIO390"

# the site_parent_link parameter is used e.g. for icon links.
site_parent_link: 'https://compbiozurich.org'
github_organisation: compbiozurich

# instructions for processing specific directories
# include:        # usually only pages in / and /_posts are "seen" => processed
#   - categories  # contains landing pages for each category
#   - tags        # contains landing pages for each tag

# Collections are used to organise pages into logical groups; these do not need
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".
# The "_posts" collection is created by default.
collections:
  doc:
    output: true
    permalink: /doc/:path/
  people:
    output: true
    permalink: /people/:path/
  course-days:
    output: true
    permalink: /course-days/:path/
collections_dir: pages  # optional; here, all collections are inside "/pages"

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout
nav_cat_blocks:     # comma-separated "label,type,label_visibility"
  general: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

# content of the different navigation blocks
# general:
#   news: "News and Updates"
#   doc: 'General Info'
#   lectures: 'Lectures'
#   people: Teachers
#   howto: 'Examples, Guides & FAQ'
#   material: 'Course Material'

related_sites:
  'UZH390 Site': 'http://www.compbiozurich.org/courses/UZH-BIO392/'
  CompbioZurich: "http://www.compbiozurich.org"
  'UZH392 course': 'http://www.compbiozurich.org/courses/UZH-BIO392/'
  'Baudisgroup at UZH': 'http://info.baudisgroup.org'

github_projects:
  'compbiozurich': 'http://github.com/compbiozurich/'
  'progenetix': 'http://github.com/progenetix/'

# The categories-date-sorted parameter determines the selection of a
# time sorted, year labeled listing template for those categories.
categories-date-sorted:
  - lectures
  - news
# As above, for tags:
tags-date-sorted:
  - days

# Only tags listed here are represented in the tag cloud.
cloud_tags:
  # - "2020"
  # - "2021"
  # - "2022"
  # - code
  # - contacts
  # - documentation
  # - days
  # - exam
  # - feedback
  # - FAQ
  # - Markdown
  # - website
  # - slides
  # - data
  # - exercises
  # - teachers

# additional Jekyll instructions
plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 4 # displayed sidebar links in current category
emptyArray: []          # dummy element for array instantiation
